### PR TITLE
Handle start message as noop in bridge

### LINKED ISSUE #163: Start message should be a nop rather than failing
New HCS orchestrators will send a start message to both Linux and Windows GCSs

### PR DESCRIPTION
**Pull request by beweedon**
The HCS will send this message to Linux VMs in the future, so we should
handle it rather than returning an error.

Resolves #163

### CODE REVIEW

File: service/gcs/bridge/bridge.go [hunk 1]
```diff
@@ -368,6 +369,20 @@ func (b *Bridge) createContainer(w ResponseWriter, r *Request) {
 	w.Write(response)
 }
 
+func (b *Bridge) startContainer(w ResponseWriter, r *Request) {
+	// This is just a noop, but needs to be handled so that an error isn't
```
Comment (jterry75) [inline service/gcs/bridge/bridge.go]: Can you add a `TODO: v4 impl required` so that I remember in two weeks :)

File: service/gcs/bridge/bridge.go [hunk 2]
```diff
@@ -197,6 +197,7 @@ type Bridge struct {
 func (b *Bridge) AssignHandlers(mux *Mux, gcs core.Core) {
 	b.coreint = gcs
 	mux.HandleFunc(prot.ComputeSystemCreateV1, b.createContainer)
+	mux.HandleFunc(prot.ComputeSystemStartV1, b.startContainer)
```
Comment (jterry75) [inline service/gcs/bridge/bridge.go]: Can you add a comment `v4 only`

File: service/gcs/bridge/bridge.go (hunk 1 above)
Comment (beweedon) [reply service/gcs/bridge/bridge.go]: Wait, do we want a V4 implementation? I wasn't sure if we were doing anything in start, and just didn't want it producing an error.

Comment (jterry75) [reply service/gcs/bridge/bridge.go]: Can you point me to the docs for how you envision the new protocol working? I guess I dont understand the ordering.

Comment (soccerGB) [reply service/gcs/bridge/bridge.go]: "The HCS will send this message to Linux VMs in the future,...."
Do you mean RS4 or RS5?

**Comment by jterry75** [comment]
Rebased on #180 but should only be merged after that.

**Comment by beweedon** [comment]
ping
